config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, as: '', path: '' do
    resources :users, only: [:new, :create, :edit, :update], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
    resources :passwords, only: [:edit, :update], path: '/password', path_names: { edit: '/' }
    get '/password_resets/edit', to: 'password_resets#edit', as: 'edit_password_reset'
    resources :password_resets, only: [:new, :create], path: '/password_resets', path_names: { new: '/' }
    patch '/password_resets', to: 'password_resets#update'
  end

  resources :pets do
    member do
      delete :destroy_photo
    end
  end
  resources :locals
  resources :cities
  resources :appointment_types

  resources :appointments do
    get 'approval_payment', to: 'appointments#approval_payment'

    post 'payment_approved', on: :member
    get 'payment_approved', on: :member
    post 'payment_unapproved', on: :member
    get 'payment_unapproved', on: :member
    #post '/payment_approved', to: 'appointments#payment_approved'
    #post 'approval_payment', to: 'appointments#payment_approved'
    #get '/payment_approval', to: 'appointments#payment_approved'
    #get '/payment_approved', to: 'appointments#payment_approved'
    #get '/payment_unapproved', to: 'appointments#payment_unapproved'
    #post '/appointments/:appointment_id/payment_approved', to: 'appointments#payment_approved', as: 'payment_approved_appointment'

  end
  resources :payments

  get 'approval_appointment', to: 'appointments#approval_appointment'

  get "/profile/:id", to: "users#show", as: "profile"
  delete "/profile/:id", to: "users#destroy"

  get '/dashboard', to: 'home#dashboard', as: 'dashboard'
  get '/dashboard_admin', to: 'home#dashboard_admin', as: 'dashboard_admin'
  get '/welcome', to: 'home#welcome', as: 'welcome'
  root to: 'home#rooting'

  post '/set_locale/:locale', to: 'application#set_locale', as: :set_locale
  get '/set_locale/:locale', to: 'application#set_locale'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/local.rb
class Local < ApplicationRecord
  has_one_attached :image
  belongs_to :city
  has_many :appointments

  validates :city_id, :address, presence: true
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize!, except: %i[show]
  before_action :set_local, only: %i[ show edit update destroy ]

  # GET /locals or /locals.json
  def index
    @locals = Local.all
  end

  # GET /locals/1 or /locals/1.json
  def show
    @current_user = current_user
    @appointment_types = AppointmentType.order(name: :asc)
  end

  # GET /locals/new
  def new
    @local = Local.new
  end

  # GET /locals/1/edit
  def edit
  end

  # POST /locals or /locals.json
  def create
    @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to local_url(@local), notice: "Local was successfully created." }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locals/1 or /locals/1.json
  def update
    respond_to do |format|
      if @local.update(local_params)
        format.html { redirect_to local_url(@local), notice: "Local was successfully updated." }
        format.json { render :show, status: :ok, location: @local }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locals/1 or /locals/1.json
  def destroy
    @local.destroy!

    respond_to do |format|
      format.html { redirect_to locals_url, notice: "Local was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_local
      @local = Local.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def local_params
      params.require(:local).permit(:city_id, :address, :image)
    end
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/views/locals/_appointment_type.html.erb
<div id="<%= dom_id appointment_type %>">
  <%= link_to new_appointment_path(appointment_type: appointment_type.name, local_id: local.id), class: "p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
    <%= render(ColorDivComponent.new(appointment_type: appointment_type)) %>
    <h3 class="font-medium text-2xl"><%= appointment_type.name %></h3>
    <p class="text-gray-500"><%= t('local_view_page') %></p>

    <% if appointment_type.payment_required? %>
      <div class="mt-3 pt-3 border-t">
        <p>
          <strong><%= AppointmentType.human_attribute_name(:payment_required) %></strong>
        </p>
        <p>
          <strong><%= AppointmentType.human_attribute_name(:price) %>:</strong>
          <%= number_to_currency(appointment_type.price) %>
        </p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/locals/_form.html.erb
<%= form_with(model: local, class: "contents") do |form| %>
  <% if local.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
        <% local.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :city_id %>
    <%= form.collection_select :city_id, City.all, :id, :name, { prompt: "Select City" }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div data-controller="previews" class="flex flex-col lg:flex-row items-center gap-5 mb-5">
    <div class="flex flex-col">
      <%= form.label :image, 'Imagen del Local', class: 'text-blue-400 font-bold text-lg' %>
      <%= form.file_field :image, direct_upload: true, data: { previews_target: "input", action: "change->previews#preview" }, class: 'flex flex-col'  %>
    </div>
    
    <% if local.image.attached? %>
      <%= image_tag local.image, class: 'avatar-preview w-full h-auto mt-2 mx-auto', data: { previews_target: "preview" } %>
    <% else %>
      <%= image_tag 'placeholder.jpg', class: 'avatar-preview', data: { previews_target: "preview" } %>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_area :address, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/locals/_local.html.erb
<div id="<%= dom_id local %>" class="flex flex-col sm:flex-row w-full rounded-lg bg-white shadow-secondary-2 border border-gray-200">
  <div class="w-full sm:w-1/2">
    <% if local.image.attached? %>
      <%= image_tag local.image, class: 'w-full h-full rounded-tl-lg rounded-bl-lg' %>
    <% else %>
      <%= image_tag 'placeholder.jpg', class: 'w-full h-full rounded-tl-lg rounded-bl-lg' %>
    <% end %>
  </div>

  <div class="w-full sm:w-1/2 ml-2 sm:ml-4">
    <div class="my-5 flex flex-col gap-5">
      <strong class="block font-medium mb-1"><%= Local.human_attribute_name(:city_id) %>:</strong>
      <p class="pl-12"><%= local.city&.name %></p>
    </div>
  
    <div class="my-5 flex flex-col gap-5">
      <strong class="block font-medium mb-1"><%= Local.human_attribute_name(:address) %>:</strong>
      <p class="pl-2 flex-wrap w-full break-words"><%= local.address %></p>
    </div>
  
    <% if action_name != "show" %>
      <div class="flex flex-row items-center justify-center sm:justify-start w-full">
        <%= link_to "Show", local, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        <%= link_to "Edit", edit_local_path(local), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    <% end %>
  </div>
</div>

app/views/locals/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing local</h1>

  <%= render "form", local: @local %>

  <%= link_to "Show this local", @local, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to locals", locals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/locals/index.html.erb
<div class="w-full sm:w-11/12 mt-8 mx-auto">
  <div class="flex justify-between items-center mb-5">
    <h1 class="font-bold text-4xl">Locals</h1>
    <%= link_to "New local", new_local_path, class: "rounded-lg py-3 px-5 bg-blue-400 text-white block font-bold" %>
  </div>

  <div id="locals" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 w-full sm:w-8/12 lg:w-10/12 mx-auto gap-7 my-10">
    <%= render @locals %>
  </div>
</div>

app/views/locals/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New local</h1>

  <%= render "form", local: @local %>

  <%= link_to "Back to locals", locals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/locals/show.html.erb
<div class="mx-auto w-full sm:w-10/12 flex h-full">
  <div class="hidden md:flex w-1/3 h-full flex-col bg-gray-200">
    <div class="w-full">
      <% if @local.image.attached? %>
        <%= image_tag @local.image, class: 'w-full h-96' %>
      <% else %>
        <%= image_tag 'placeholder.jpg', class: 'w-full h-96' %>
      <% end %>
    </div>
    <div class="w-full flex-col items-center">
      <div class="my-5 flex flex-col gap-5 pl-4">
        <strong class="block font-medium mb-1">City:</strong>
        <p class="pl-12"><%= @local.city&.name %></p>
      </div>
    
      <div class="my-5 flex flex-col gap-5 pl-4">
        <strong class="block font-medium mb-1">Address:</strong>
        <p class="pl-2 flex-wrap w-full break-words"><%= @local.address %></p>
      </div>
    </div>
  </div>

  <div class="w-full md:w-2/3 h-full ml-10 mt-10">
    <h2 class="text-2xl font-bold text-blue-400"><%= t('local_show') %>:</h2>
  
    <div class="grid grid-cols-3 gap-6 px-8 pt-8">
      <% @appointment_types.each do |appointment_type| %>
        <%= render "locals/appointment_type", appointment_type: appointment_type, local: @local %>
      <% end %>
    </div>
  
    <% if @current_user.admin?%>
      <div class="flex gap-6 ml-2 mt-8">
        <%= link_to "Edit this local", edit_local_path(@local), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        <%= button_to "Destroy this local", local_path(@local), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
    <% end %>
    <%= link_to "Back", dashboard_path, class: "my-5 ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>