config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, as: '', path: '' do
    resources :users, only: [:new, :create, :edit, :update], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
    resources :passwords, only: [:edit, :update], path: '/password', path_names: { edit: '/' }
    get '/password_resets/edit', to: 'password_resets#edit', as: 'edit_password_reset'
    resources :password_resets, only: [:new, :create], path: '/password_resets', path_names: { new: '/' }
    patch '/password_resets', to: 'password_resets#update'
  end

  resources :pets do
    member do
      delete :destroy_photo
    end
  end
  resources :locals
  resources :cities
  resources :appointment_types

  resources :appointments do
    get 'approval_payment', to: 'appointments#approval_payment'

    post 'payment_approved', on: :member
    get 'payment_approved', on: :member
    post 'payment_unapproved', on: :member
    get 'payment_unapproved', on: :member
    #post '/payment_approved', to: 'appointments#payment_approved'
    #post 'approval_payment', to: 'appointments#payment_approved'
    #get '/payment_approval', to: 'appointments#payment_approved'
    #get '/payment_approved', to: 'appointments#payment_approved'
    #get '/payment_unapproved', to: 'appointments#payment_unapproved'
    #post '/appointments/:appointment_id/payment_approved', to: 'appointments#payment_approved', as: 'payment_approved_appointment'

  end
  resources :payments

  get 'approval_appointment', to: 'appointments#approval_appointment'

  get "/profile/:id", to: "users#show", as: "profile"
  delete "/profile/:id", to: "users#destroy"

  get '/dashboard', to: 'home#dashboard', as: 'dashboard'
  get '/dashboard_admin', to: 'home#dashboard_admin', as: 'dashboard_admin'
  get '/welcome', to: 'home#welcome', as: 'welcome'
  root to: 'home#rooting'

  post '/set_locale/:locale', to: 'application#set_locale', as: :set_locale
  get '/set_locale/:locale', to: 'application#set_locale'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/appointment_types_controller.rb
class AppointmentTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize!
  before_action :set_appointment_type, only: %i[ show edit update destroy ]

  # GET /appointment_types or /appointment_types.json
  def index
    @appointment_types = AppointmentType.all
  end

  # GET /appointment_types/1 or /appointment_types/1.json
  def show
  end

  # GET /appointment_types/new
  def new
    @appointment_type = AppointmentType.new
  end

  # GET /appointment_types/1/edit
  def edit
  end

  # POST /appointment_types or /appointment_types.json
  def create
    @appointment_type = current_user.appointment_types.new(appointment_type_params.merge(user: current_user))

    respond_to do |format|
      if @appointment_type.save
        format.html { redirect_to appointment_type_url(@appointment_type), notice: "Appointment type was successfully created." }
        format.json { render :show, status: :created, location: @appointment_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointment_types/1 or /appointment_types/1.json
  def update
    respond_to do |format|
      if @appointment_type.update(appointment_type_params)
        format.html { redirect_to appointment_type_url(@appointment_type), notice: "Appointment type was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointment_types/1 or /appointment_types/1.json
  def destroy
    @appointment_type.destroy!

    respond_to do |format|
      format.html { redirect_to appointment_types_url, notice: "Appointment type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment_type
      @appointment_type = AppointmentType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_type_params
      params.require(:appointment_type).permit(:payment_required, :name, :user_id, :price, :description)
    end
end

app/helpers/appointment_types_helper.rb
module AppointmentTypesHelper
end

app/views/appointment_types/_appointment_type.html.erb
<div id="<%= dom_id appointment_type %>">
  <p class="my-5 flex gap-5">
    <strong class="block font-medium mb-1"><%= AppointmentType.human_attribute_name(:payment_required) %>:</strong>
    <%= appointment_type.payment_required %>
  </p>

  <p class="my-5 flex gap-5">
    <strong class="block font-medium mb-1"><%= AppointmentType.human_attribute_name(:name) %>:</strong>
    <%= appointment_type.name %>
  </p>

  <p class="my-5 flex gap-5">
    <strong class="block font-medium mb-1"><%= AppointmentType.human_attribute_name(:user_id) %>:</strong>
    <%= appointment_type.user.first_name %>
  </p>

  <p class="my-5 flex gap-5">
    <strong class="block font-medium mb-1"><%= AppointmentType.human_attribute_name(:price) %>:</strong>
    <%= number_to_currency(appointment_type.price) %>
  </p>

  <p class="my-5 flex gap-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= appointment_type.description %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this appointment type", appointment_type, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this appointment type", edit_appointment_type_path(appointment_type), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/appointment_types/_form.html.erb
<%= form_with(model: appointment_type, class: "contents") do |form| %>
  <% if appointment_type.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(appointment_type.errors.count, "error") %> prohibited this appointment_type from being saved:</h2>

      <ul>
        <% appointment_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :payment_required %>
    <%= form.check_box :payment_required, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/appointment_types/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing appointment type</h1>

  <%= render "form", appointment_type: @appointment_type %>

  <%= link_to "Show this appointment type", @appointment_type, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to appointment types", appointment_types_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/appointment_types/index.html.erb
<div class="w-full sm:w-11/12 mt-8 mx-auto">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Appointment types</h1>
    <%= link_to "New appointment type", new_appointment_type_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="appointment_types" class="min-w-full">
    <%= render @appointment_types %>
  </div>
</div>

app/views/appointment_types/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New appointment type</h1>

  <%= render "form", appointment_type: @appointment_type %>

  <%= link_to "Back to appointment types", appointment_types_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/appointment_types/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @appointment_type %>

    <%= link_to "Edit this appointment_type", edit_appointment_type_path(@appointment_type), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this appointment_type", appointment_type_path(@appointment_type), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to appointment_types", appointment_types_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>