config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, as: '', path: '' do
    resources :users, only: [:new, :create, :edit, :update], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
    resources :passwords, only: [:edit, :update], path: '/password', path_names: { edit: '/' }
    get '/password_resets/edit', to: 'password_resets#edit', as: 'edit_password_reset'
    resources :password_resets, only: [:new, :create], path: '/password_resets', path_names: { new: '/' }
    patch '/password_resets', to: 'password_resets#update'
  end

  resources :pets do
    member do
      delete :destroy_photo
    end
  end
  resources :locals
  resources :cities
  resources :appointment_types

  resources :appointments do
    get 'approval_payment', to: 'appointments#approval_payment'

    post 'payment_approved', on: :member
    get 'payment_approved', on: :member
    post 'payment_unapproved', on: :member
    get 'payment_unapproved', on: :member
    #post '/payment_approved', to: 'appointments#payment_approved'
    #post 'approval_payment', to: 'appointments#payment_approved'
    #get '/payment_approval', to: 'appointments#payment_approved'
    #get '/payment_approved', to: 'appointments#payment_approved'
    #get '/payment_unapproved', to: 'appointments#payment_unapproved'
    #post '/appointments/:appointment_id/payment_approved', to: 'appointments#payment_approved', as: 'payment_approved_appointment'

  end
  resources :payments

  get 'approval_appointment', to: 'appointments#approval_appointment'

  get "/profile/:id", to: "users#show", as: "profile"
  delete "/profile/:id", to: "users#destroy"

  get '/dashboard', to: 'home#dashboard', as: 'dashboard'
  get '/dashboard_admin', to: 'home#dashboard_admin', as: 'dashboard_admin'
  get '/welcome', to: 'home#welcome', as: 'welcome'
  root to: 'home#rooting'

  post '/set_locale/:locale', to: 'application#set_locale', as: :set_locale
  get '/set_locale/:locale', to: 'application#set_locale'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flash.html.erb
<% if alert || notice %>
  <% color = alert ? 'bg-red-400' : 'bg-green-400' %>
  <div class="fixed top-0 inset-x-0 m-4 z-30 pointer-events-none">
    <div class="flex flex-col items-end space-y-4">
      <div data-controller="alert" data-alert-dismiss-after-value="3000" data-alert-show-class="translate-x-0 opacity-100" data-alert-hide-class="translate-x-full opacity-0" class="ease-in-out duration-500 max-w-sm w-full shadow-lg rounded px-4 py-3 relative <%= color %> text-white pointer-events-auto translate-x-0 opacity-100">
        <div class="p-2">
          <div class="flex items-start">
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm leading-5 font-medium">
                <%= alert || notice %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button data-action="alert#close" class="inline-flex text-white focus:outline-none focus:text-gray-300 transition ease-in-out duration-150">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="bg-gradient-to-r from-blue-400 to-teal-500 flex justify-between items-center py-4 px-2" data-controller="menu">
   
  <%= link_to root_path do %>
    <h1 class="text-3xl font-bold text-white"><%= t('app_name') %></h1>
  <% end %>

  <button class="sm:hidden text-white" data-action="click->menu#toggle"><%= image_tag 'svg/menu.svg', width: 35, height: 35, class: 'text-white' %></button>

  <div class="hidden sm:block">
    <%= render partial: 'shared/items' %>
  </div>
  
  <!-- Menu mobile -->
  <div class="fixed gap-4 flex sm:hidden bg-gradient-to-r from-blue-400 to-teal-500 top-0 right-0 shadow z-11 h-full  flex-col min-w-[45%] w-1/2 overflow-y-scroll ease-in-out duration-200 p-5 translate-x-full" data-menu-target="items">
    <div data-action="click->menu#toggle" class="fixed z-10 w-1/2 h-full top-0 left-0 bg-black bg-opacity-40"></div>
    <button class="mb-4" data-action="click->menu#toggle"><%= image_tag 'svg/close.svg', width: 35, height: 35 %></button>
    <%= render partial: 'shared/items' %>
  </div>
</div>

app/views/shared/_items.html.erb
  
  <%= link_to set_locale_path(locale: 'en'), method: :post, class: "inline-block mr-3" do %>
      <%= image_tag("svg/uk-flag.svg", title: "English", alt: "English", class: 'w-5') %>
    <% end %>

    <%= link_to set_locale_path(locale: 'pt-BR'), method: :post, class: "inline-block mr-3" do %>
      <%= image_tag("svg/brazil-flag.svg", title: "Portuguese", alt: "Português", class: "w-5") %>
    <% end %>

    <%= link_to set_locale_path(locale: 'es'), method: :post, class: "inline-block mr-3" do %>
      <%= image_tag("svg/spain-flag.svg", title: "Spanish", alt: "Español", class: "w-5") %>
    <% end %>

  <% if user_signed_in? %>
    
    <%= link_to 'Edit', edit_user_path(current_user.id), class: "mx-2 text-white hover:text-gray-200 font-bold text-xl" %>
    <%= link_to 'Log out', session_path(current_user), class: "mx-2 text-white hover:text-gray-200 font-bold text-xl", method: :delete, data: {
      turbo_method: :delete,
      turbo_confirm: 'Are you sure?'
    } %>
  <% else %>
    <%= link_to 'Log in', new_session_path, class: "mx-2 text-white hover:text-gray-200 font-bold text-xl" %>
    <%= link_to 'Sign up', new_user_path, class: "mx-2 bg-white text-blue-500 px-4 py-2 rounded-full hover:bg-blue-400 hover:text-white transition duration-300 font-bold" %>
  <% end %>