config/routes.rb
Rails.application.routes.draw do
  namespace :authentication, as: '', path: '' do
    resources :users, only: [:new, :create, :edit, :update], path: '/register', path_names: { new: '/' }
    resources :sessions, only: [:new, :create, :destroy], path: '/login', path_names: { new: '/' }
    resources :passwords, only: [:edit, :update], path: '/password', path_names: { edit: '/' }
    get '/password_resets/edit', to: 'password_resets#edit', as: 'edit_password_reset'
    resources :password_resets, only: [:new, :create], path: '/password_resets', path_names: { new: '/' }
    patch '/password_resets', to: 'password_resets#update'
  end

  resources :pets do
    member do
      delete :destroy_photo
    end
  end
  resources :locals
  resources :cities
  resources :appointment_types

  resources :appointments do
    get 'approval_payment', to: 'appointments#approval_payment'

    post 'payment_approved', on: :member
    get 'payment_approved', on: :member
    post 'payment_unapproved', on: :member
    get 'payment_unapproved', on: :member
    #post '/payment_approved', to: 'appointments#payment_approved'
    #post 'approval_payment', to: 'appointments#payment_approved'
    #get '/payment_approval', to: 'appointments#payment_approved'
    #get '/payment_approved', to: 'appointments#payment_approved'
    #get '/payment_unapproved', to: 'appointments#payment_unapproved'
    #post '/appointments/:appointment_id/payment_approved', to: 'appointments#payment_approved', as: 'payment_approved_appointment'

  end
  resources :payments

  get 'approval_appointment', to: 'appointments#approval_appointment'

  get "/profile/:id", to: "users#show", as: "profile"
  delete "/profile/:id", to: "users#destroy"

  get '/dashboard', to: 'home#dashboard', as: 'dashboard'
  get '/dashboard_admin', to: 'home#dashboard_admin', as: 'dashboard_admin'
  get '/welcome', to: 'home#welcome', as: 'welcome'
  root to: 'home#rooting'

  post '/set_locale/:locale', to: 'application#set_locale', as: :set_locale
  get '/set_locale/:locale', to: 'application#set_locale'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!, only: [:dashboard, :dashboard_admin]
  before_action :authorize!, only: [:dashboard_admin]

  def rooting
    if user_signed_in? && current_user.client?
      redirect_to dashboard_path
    elsif user_signed_in? && (current_user.admin? || current_user.stylist?)
      redirect_to dashboard_admin_path
    else
      redirect_to welcome_path
    end
  end

  def welcome
  end

  def dashboard
    @cities = City.all
    if params[:city_id].present?
      @locals = Local.where(city_id: params[:city_id])
    else
      @locals = Local.all
    end
    @appointments = current_user.appointments.order(created_at: :desc).limit(5)
  end

  def dashboard_admin
    @appointments = Appointment.order(created_at: :desc)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_appointments.html.erb
<tr id="<%= dom_id appointment %>">
  <td data-label="Pet Name" class="border border-slate-300 bg-white text-left p-4"><%= appointment.appointment_code %></td>
  <td data-label="Status" class="border border-slate-300 bg-white text-left p-4">
    
      <%= form_with(model: appointment, method: :patch) do |form| %>
        <% if appointment.payments&.first.billing_status == "approved" %>
          <%= form.select :status, options_for_select(Appointment.statuses.map { |key, value| [key.capitalize, key] }, form.object.status), {}, { onchange: "this.form.submit()"} %>
        <% else %>
          <%= t("enum.appointment.status.#{appointment.status}") %>
        <% end %>

    <% end %>
  </td>
  <td data-label="Pet Name" class="border border-slate-300 bg-white text-left p-4"><%= appointment.pet&.name %></td>
  <td data-label="Breed" class="border border-slate-300 bg-white text-left p-4"><%= appointment.pet&.breed %></td>
  <td data-label="Kind" class="border border-slate-300 bg-white text-left p-4"><%= appointment.pet&.kind %></td>
  <td data-label="Starts" class="border border-slate-300 bg-white text-left p-4"><%= appointment.start_at.strftime('%b %e, %Y at %l:%M %p') %></td>
  <td data-label="Ends" class="border border-slate-300 bg-white text-left p-4"><%= appointment.end_at.strftime('%b %e, %Y at %l:%M %p') %></td>
  <td data-label="Appointment Type" class="border border-slate-300 bg-white text-left p-4"><%= appointment.appointment_type.name %></td>
  
    <% if appointment.payments&.any? %>
      <% if appointment.payments&.first.billing_status == "onapproval" %>
        <td data-label="Paid" style="background-color: rgba(255, 0, 0, 0.5);" class="border border-slate-500 bg-red-900 text-left p-4">
        <%= link_to appointment_approval_payment_path(appointment.id, local_id: appointment.local_id) do %>
          <%= t("enum.payment.billing_status.#{appointment.payments&.first.billing_status}") %>
        <% end %>
      <% else %>
        <td data-label="Paid" class="border border-slate-500 bg-white text-left p-4">
          <%= t("enum.payment.billing_status.#{appointment.payments&.first.billing_status}") %>
      <% end %>
    <% else %>
      <%= "No required" %>
    <% end %>
  </td>
</tr>

app/views/home/_locals.html.erb
<div id="<%= dom_id local_obj %>">
  <%= link_to local_path(local_obj), class:"p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do%>
    <% if local_obj.image.attached? %>
      <%= image_tag local_obj.image, class: 'w-full h-80 rounded-lg' %>
    <% else %>
      <%= image_tag 'placeholder.jpg', class: 'w-full h-80 rounded-lg' %>
    <% end %>
    <p class="my-5 flex flex-col items-start justify-center">
      <strong><%= t('dashboard_local') %>: </strong>
      <%= local_obj.city.name %>
    </p>
  <% end %>
</div>

app/views/home/dashboard.html.erb
<div class="w-screen lg:w-9/12 mx-auto p-5 mt-3 rounded shadow-xl border">
  <div class="flex justify-between items-center items-centerpx-6 py-10 rounded-t-xl bg-gray-50">
    <div>
    <h1 class="text-3xl font-extrabold text-center"><%= current_user.first_name %>'s <%= t('dashboard_client') %></h1>
    <p class="text-center text-gray-600 mt-2"><%= t('description_client') %></p>
    </div>
    <div class="my-5 justify-end items-center w-1/5">
      <%= link_to "Pet(s)", pets_path, class: "rounded-lg py-3 px-5 bg-blue-400 text-white block font-bold" %>
    </div>
  </div>
  

  <div class="flex overflow-x-scroll xl:overflow-x-hidden gap-2 my-4">
    <%= render(CityComponent.new) %>

    <%= render(CityComponent.with_collection(@cities)) %>
  </div>

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 px-8 pt-8">
    <% @locals.each do |local_obj| %>
      <%= render "home/locals", local_obj: local_obj %>
    <% end %>
  </div>
  <div>
    <h3 class="font-bold text-2xl mb-6 mt-10 pt-10 border-t border-slate-2"><%= t('dashboard_list')%></h3>
    <table class="w-full table">
      <thead>
        <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('appointment_code') %></th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('status') %></th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('pet_name') %></th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('breed') %></th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('kind') %></th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('starts') %></th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('ends') %></th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('appointment_type') %></th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('paid') %></th>
      </thead>
      <tbody>
        <%= render @appointments %>
      </tbody>
    </table>

    <div class="flex justify-end mt-4">
      <%= link_to "View all appointments", profile_path(current_user.id), class: "rounded-lg py-3 px-5 bg-blue-400 text-white block font-bold" %>
    </div>
  </div>
</div>

app/views/home/dashboard_admin.html.erb
<div class="w-full lg:w-10/12 mx-auto p-5 mt-3 rounded shadow-xl border">
 
  <div class="px-6 py-10 rounded-t-xl bg-gray-50">
    <h1 class="text-3xl font-extrabold text-center"><%= current_user.first_name %>'s <%= t('dashboard_admin') %></h1>
    <p class="text-center text-gray-600 mt-2"><%= t('description_admin') %> </p>
  </div>

  <div class="my-5 flex justify-between items-center gap-5">
    <div class="flex flex-col sm:flex-row gap-5 items-center justify-between">
      <%= link_to "My Cities", cities_path, class: "rounded-lg py-3 px-5 bg-blue-400 text-white block font-bold" %>
      <%= link_to "New City", new_city_path, class: "rounded-lg py-3 px-5 bg-blue-400 text-white block font-bold" %>
    </div>

    <div class="flex flex-col sm:flex-row gap-5 items-center justify-between">
      <%= link_to "My Locals", locals_path, class: "rounded-lg py-3 px-5 bg-blue-400 text-white block font-bold" %>
      <%= link_to "New Local", new_local_path, class: "rounded-lg py-3 px-5 bg-blue-400 text-white block font-bold" %>
    </div>

    <div class="flex flex-col sm:flex-row gap-5 items-center justify-between">
      <%= link_to "My Appointment Types", appointment_types_path, class: "rounded-lg py-3 px-5 bg-blue-400 text-white block font-bold w-max" %>
      <%= link_to "New Appointment Type", new_appointment_type_path, class: "rounded-lg py-3 px-5 bg-blue-400 text-white block font-bold" %>
    </div>
  </div>
  
  <div class="mt-4">
    <div class="my-5 flex justify-between items-center gap-5">
      <div class="flex justify-start  border-t border-slate-2 gap-5 pt-5">
        <%= link_to "View all appointments", appointments_path, class: "bg-blue-400 text-white rounded p-4 font-bold" %>
        <%= link_to "View all approval for appointments", approval_appointment_path, class: "bg-blue-400 text-white rounded p-4 font-bold" %>
      </div>
    </div>
    <% if @appointments.scheduled.any? %>
      <h3 class="font-bold text-2xl mb-6 pt-10"><%= t('scheduled_appointment') %></h3>
      <table class="w-full table">
        <thead>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('appointment_code') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('status') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('pet_name') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('breed') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('kind') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('starts') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('ends') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('appointment_type') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('paid') %></th>
        </thead>
        <tbody>
          <% @appointments.scheduled.limit(8).each do |appointment| %>
            <%= render "home/appointments", appointment: appointment %>
          <% end %>
        </tbody>
      </table>
      
    <% end %>

    <% if @appointments.processing.any? %>
      <h3 class="font-bold text-2xl mb-6 mt-10 pt-10 border-t border-slate-2"><%= t('process_appointment') %></h3>
      <table class="w-full table">
        <thead>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('appointment_code') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('status') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('pet_name') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('breed') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('kind') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('starts') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('ends') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('appointment_type') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('paid') %></th>
        </thead>
        <tbody>
          <% @appointments.processing.limit(8).each do |appointment| %> 
            <%= render "home/appointments", appointment: appointment %>
          <% end %>
        </tbody>
      </table>
    <% end %>

    <% if @appointments.finished.any? %>
      <h3 class="font-bold text-2xl mb-6 mt-10 pt-10 border-t border-slate-2"><%= t('finish_appointment') %> </h3>
      <table class="w-full table">
        <thead>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('appointment_code') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('status') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('pet_name') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('breed') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('kind') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('starts') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('ends') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('appointment_type') %></th>
          <th class="border border-slate-300 p-3 text-left bg-slate-50"><%= t('paid') %></th>
        </thead>
        <tbody>
          <% @appointments.finished.limit(8).each do |appointment| %>
            <%= render "home/appointments", appointment: appointment %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </divmt-4>
</div>

app/views/home/welcome.html.erb
<div class="flex flex-col md:flex-row items-center justify-between px-6 py-12 bg-white">
  <div class="md:w-1/2 mb-8 md:mb-0 text-center md:text-left">
    <h1 class="text-3xl md:text-5xl font-bold bg-gradient-to-r from-blue-400 to-teal-500 text-transparent bg-clip-text mb-4"><%= t('welcome_title') %> </h1>
    <p class="text-lg text-gray-700 my-4"><%= t('welcome_description') %></p>
    <% if user_signed_in? %>
      <%= link_to 'Reservar', dashboard_path, class: "rounded-lg py-3 px-5 bg-blue-400 text-white block font-bold my-5 w-min text-2xl" %>
    <% else %>
      <%= link_to 'Reservar', new_session_path, class: "rounded-lg py-3 px-5 bg-blue-400 text-white block font-bold my-5 w-min text-2xl" %>
    <% end %>
  </div>
  <div class="md:w-1/2">
    <%= image_tag('svg/bichos.svg', alt: 'Mascota', class: 'w-full') %>
  </div>
</div>